### ISSUE TITLE
Mercurial cristal wand bugs

### ISSUE THREAD

**Issue by supermassimo** [Lycaonj/AdvancedThaumaturgy#15]
there are 2 issues with this wand, the first one is that in TC 4.1, the wand is named "unknown" instead of "mercurial cristal wand", and the 2nd issue is that when you go to the thaumonomicon page of the mercurial cristal wand it crashes when you put the mouse on top of the wand, I dont know if its just me or everyone is having this problem in 4.1

Crash report:
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 21/02/14 03:26 PM
Description: Rendering screen

java.lang.NoSuchMethodError: thaumcraft.common.items.wands.WandManager.getTotalVisDiscount(Lnet/minecraft/entity/player/EntityPlayer;)F
    at net.ixios.advancedthaumaturgy.items.ItemMercurialWand.func_77624_a(ItemMercurialWand.java:233)
    at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:663)
    at thaumcraft.client.gui.GuiResearchRecipe.drawInfusionPage(GuiResearchRecipe.java:1287)
    at thaumcraft.client.gui.GuiResearchRecipe.drawPage(GuiResearchRecipe.java:352)
    at thaumcraft.client.gui.GuiResearchRecipe.genResearchBackground(GuiResearchRecipe.java:263)
    at thaumcraft.client.gui.GuiResearchRecipe.func_73863_a(GuiResearchRecipe.java:218)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1036)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:946)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

**Comment by Lycaonj** [comment]
As mentioned on the forum post, AT is currently for 4.0.5b, not 4.1.
