### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by Baron-Abner** [Lycaonj/AdvancedThaumaturgy#32]
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 3/22/14 11:50 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.AbstractMethodError: net.ixios.advancedthaumaturgy.compat.energy.BCCompatChecker.register()V
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:156)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:523)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:183)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:473)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
Caused by: java.lang.AbstractMethodError: net.ixios.advancedthaumaturgy.compat.energy.BCCompatChecker.register()V
    at net.ixios.advancedthaumaturgy.AdvThaum.preInit(AdvThaum.java:213)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:545)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:522)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 8 (amd64) version 6.2
    Java Version: 1.7.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 263682832 bytes (251 MB) / 469237760 bytes (447 MB) up to 954466304 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 14 mods loaded, 14 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{6.4.49.965} [Forge Mod Loader](minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized
    Forge{9.11.1.965} [Minecraft Forge](minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{0.9.0.9} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.6.1.9} [Not Enough Items](NotEnoughItems 1.6.1.9.jar) Unloaded->Constructed->Pre-initialized
    TConstruct-Preloader{0.0.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed->Pre-initialized
    Forestry{2.3.1.1} [Forestry for Minecraft](forestry-A-2.3.1.1.jar) Unloaded->Constructed->Pre-initialized
    Thaumcraft{4.1.0g} [Thaumcraft](Thaumcraft4.1.0g.zip) Unloaded->Constructed->Pre-initialized
    AdvancedThaumaturgy{0.0.25} [Advanced Thaumaturgy](AdvancedThaumaturgy-1.6.4-0.0.25.jar) Unloaded->Constructed->Errored
    TConstruct{1.6.X_1.5.4dev} [Tinkers' Construct](TConstruct_mc1.6.4_1.5.4d4.jar) Unloaded->Constructed->Pre-initialized
    ThaumicTinkererKami{1.0} [Thaumic Tinkerer KAMI](ThaumicTinkererKAMI_j6.jar) Unloaded->Constructed->Pre-initialized
    ThaumicTinkerer{2.3-137} [Thaumic Tinkerer](ThaumicTinkerer-2.3-137.jar) Unloaded->Constructed->Pre-initialized
    MagicBees{2.1.12} [Magic Bees](magicbees-2.1.12.jar) Unloaded->Constructed->Pre-initialized
    ThaumicExploration{0.5.1} [Thaumic Exploration](Thaumic Exploration 0.5.2.jar) Unloaded->Constructed->Pre-initialized
    TConstruct Environment: Sane and ready for action. Bugs may be reported.

**Comment by Lycaonj** [comment]
I think I have this fixed in build 26.  Please reopen the issue if it's not :)
