### ISSUE TITLE
0.0.28: client freezes and closes when dying on hardcore.

### ISSUE THREAD

**Issue by Roadcrosser** [Lycaonj/AdvancedThaumaturgy#49]
```
2014-07-27 11:22:22 [INFO] [STDERR] java.io.FileNotFoundException: C:\<path>\minecraft\saves\New World\advthaum_infusion.dat (The system cannot find the path specified)
2014-07-27 11:22:22 [INFO] [STDERR]     at java.io.FileOutputStream.open(Native Method)
2014-07-27 11:22:22 [INFO] [STDERR]     at java.io.FileOutputStream.<init>(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at java.io.FileOutputStream.<init>(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.writeCacheCompound(Utilities.java:64)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:54)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.TickManager.saveData(TickManager.java:73)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.proxies.CommonProxy.saveData(CommonProxy.java:87)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.AdvThaum.serverStopping(AdvThaum.java:358)
2014-07-27 11:22:22 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2014-07-27 11:22:22 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:545)
2014-07-27 11:22:22 [INFO] [STDERR]     at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
2014-07-27 11:22:22 [INFO] [STDERR]     at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2014-07-27 11:22:22 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
2014-07-27 11:22:22 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
2014-07-27 11:22:22 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.post(EventBus.java:267)
2014-07-27 11:22:22 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
2014-07-27 11:22:22 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
2014-07-27 11:22:22 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2014-07-27 11:22:22 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
2014-07-27 11:22:22 [INFO] [STDERR]     at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2014-07-27 11:22:22 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
2014-07-27 11:22:22 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
2014-07-27 11:22:22 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.post(EventBus.java:267)
2014-07-27 11:22:22 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
2014-07-27 11:22:22 [INFO] [STDERR]     at cpw.mods.fml.common.Loader.serverStopping(Loader.java:767)
2014-07-27 11:22:22 [INFO] [STDERR]     at cpw.mods.fml.common.FMLCommonHandler.handleServerStopping(FMLCommonHandler.java:324)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:490)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
2014-07-27 11:22:22 [INFO] [STDERR] java.io.FileNotFoundException: C:\Users\Conor\Desktop\Multimc\instances\Hardcore Ren\minecraft\saves\New World\advthaum_infusion.dat (The system cannot find the path specified)
2014-07-27 11:22:22 [INFO] [STDERR]     at java.io.FileOutputStream.open(Native Method)
2014-07-27 11:22:22 [INFO] [STDERR]     at java.io.FileOutputStream.<init>(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at java.io.FileOutputStream.<init>(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.writeCacheCompound(Utilities.java:64)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:54)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.Utilities.getCacheCompound(Utilities.java:55)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.misc.TickManager.saveData(TickManager.java:73)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.proxies.CommonProxy.saveData(CommonProxy.java:87)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.ixios.advancedthaumaturgy.AdvThaum.serverStopping(AdvThaum.java:358)
2014-07-27 11:22:22 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2014-07-27 11:22:22 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:545)
2014-07-27 11:22:22 [INFO] [STDERR]     at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
2014-07-27 11:22:22 [INFO] [STDERR]     at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2014-07-27 11:22:22 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
2014-07-27 11:22:22 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
2014-07-27 11:22:22 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.post(EventBus.java:267)
2014-07-27 11:22:22 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
2014-07-27 11:22:22 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
2014-07-27 11:22:22 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2014-07-27 11:22:22 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
2014-07-27 11:22:22 [INFO] [STDERR]     at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2014-07-27 11:22:22 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
2014-07-27 11:22:22 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
2014-07-27 11:22:22 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.post(EventBus.java:267)
2014-07-27 11:22:22 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
2014-07-27 11:22:22 [INFO] [STDERR]     at cpw.mods.fml.common.Loader.serverStopping(Loader.java:767)
2014-07-27 11:22:22 [INFO] [STDERR]     at cpw.mods.fml.common.FMLCommonHandler.handleServerStopping(FMLCommonHandler.java:324)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:490)
2014-07-27 11:22:22 [INFO] [STDERR]     at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
2014-07-27 11:22:22 [INFO] [STDERR] java.io.FileNotFoundException: C:\<path>\minecraft\saves\New World\advthaum_infusion.dat (The system cannot find the path specified)
2014-07-27 11:22:22 [INFO] [STDERR]     at java.io.FileOutputStream.open(Native Method)
2014-07-27 11:22:22 [INFO] [STDERR]     at java.io.FileOutputStream.<init>(Unknown Source)
2014-07-27 11:22:22 [INFO] [STDERR]     at java.io.FileOutputStream.<init>(Unknown Source)
```

Also, the WIP forum thread doesn't link to the 1.7.2 one so I didn't know it updated or anything.

**Comment by Lycaonj** [comment]
I'm moving straight to 1.7.10, got a test build on the forum post. -- Sorry this reply is months behind.  Health has been terrible and I am just now getting back into things.  If this is still an issue in 1.7.10 (after the build for it is posted) feel free to reopen.
